### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by darrylhebbes** [jamescherti/minimal-emacs.d#1]
Hi, thanks for a great starter and performant setup.

I have a question... and maybe I am missing something, but are post-early-init.el and pre-init.el the same file in terms of the logic?
Or is the separation in names simply semantic?

1. pre-early-init.el
2. * early-init.el
3. post-early-init.el   <- between early-init.el and init.el
4. pre-init.el <- between early-init.el and init.el
5. * init.el
6. post-init.el

Perhaps this explains my thinking

1. pre-early-init.el
2. * early-init.el
3. bridge-init.el  <- between early-init.el and init.el, also `inter-init.el`, `transition-init.el`
4. * init.el
5. post-init.el

I was just curious.

**Comment by jamescherti** [comment]
I'm glad you found the setup useful, @darrylhebbes! I appreciate your question and I will add it to the `README.md` file.

During the execution of `early-init.el` (and `pre-early-init.el` and  `post-early-init.el`), Emacs has not yet loaded the graphical user interface (GUI). This file is used for configurations that need to be applied before the GUI is initialized, such as settings that affect the early stages of the Emacs startup process.

Thus, `post-early-init.el` and `pre-init.el` serve different purposes and are not the same.

**Comment by darrylhebbes** [comment]
Ah ok, thanks makes sense. Its good to keep it conceptually separated.
