### ISSUE TITLE
Removing `confirm-kill-emacs` variable from `init.el`

### ISSUE THREAD

**Issue by paniash** [jamescherti/minimal-emacs.d#14]
Hi,

I was wondering if there is a way to disable the following line in `init.el`:
```emacs-lisp
(setq confirm-kill-emacs 'y-or-n-p)
```

As it is mentioned to never modify the `init.el` and `early-init.el` files.

**Comment by jamescherti** [comment]
You could have modified this variable in `~/.emacs.d/post-init.el`. 

However, this variable doesn't belong in `minimal-emacs.d` as it's more appropriate for users to configure it according to their own preferences. 

Thank you for pointing this out. I've removed the variable in the latest version of `minimal-emacs.d`.
