### ISSUE TITLE
How to add a new menu + item?

### ISSUE THREAD

**Issue by eborgbjerg** [jamescherti/minimal-emacs.d#17]
I added this to pre-early-init.el to enable the Menu Bar:

;;; pre-early-init.el --- DESCRIPTION -*- no-byte-compile: t; lexical-binding: t; -*-
(setq minimal-emacs-ui-features '(context-menu tool-bar menu-bar dialogs tooltips))

and that works fine as expected.

Then, to add a new menu with items, I also added this to post-init.el:

;;; post-init.el --- Called from end of init.el -*- no-byte-compile: t; lexical-binding: t; -*-
(define-key global-map [menu-bar words]
	    (cons "Words" (make-sparse-keymap "Words")))

 ;; Define specific subcommands in this menu.
(define-key global-map
  [menu-bar words forward]
  '("Forward word" . forward-word))

But the new menu 'Words' does not show up.
Executing the code from ielm/REPL does create the new menu.

Maybe I missed something?

**Comment by jamescherti** [comment]
Hello @eborgbjerg,

The menu is activated during `early-init.el`.

Try adding menu items in `post-early-init.el`; it should work.

**Comment by eborgbjerg** [comment]
Yes, that works great.
Thank you very much!

**Comment by jamescherti** [comment]
You're very welcome, @eborgbjerg!
