### ISSUE TITLE
Theme loading question

### ISSUE THREAD

**Issue by eborgbjerg** [jamescherti/minimal-emacs.d#18]
I tried to add this snippet:

(use-package tomorrow-night-deepblue-theme
  :ensure t
  :config
  ;; Disable all themes and load the Tomorrow Night Deep Blue theme
  (mapc #'disable-theme custom-enabled-themes)
  (load-theme 'tomorrow-night-deepblue t))

Adding it to post-early-init triggered this message in a Warnings buffer:
Error (use-package): Cannot load tomorrow-night-deepblue-theme

while adding it to post-init.el had no effect.

Evaluating the snippet in an ielm buffer after startup has the expected effect though.

Probably I have missed something...?

**Comment by jamescherti** [comment]
Hello @eborgbjerg,

It is because packages are initialized and updated by `init.el`.

If you want packages to be loaded by `early-init.el`, add this to `post-early-init.el`:
```elisp
(setq minimal-emacs-package-initialize-and-refresh nil)

;; Initialize packages in here instead of init.el
(progn
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (eval-when-compile
    (require 'use-package)))

(use-package tomorrow-night-deepblue-theme
  :ensure t
  :config
  ;; Disable all themes and load the Tomorrow Night Deep Blue theme
  (mapc #'disable-theme custom-enabled-themes)
  (load-theme 'tomorrow-night-deepblue t))
```

The drawback is that if a package fails, you will not be able to see anything in the Emacs GUI. You will need to open the terminal to view Emacs's stdout.

**Comment by eborgbjerg** [comment]
Hello James,

With the above in post-early-init.el the blue background appears at first, but the default colors reappear immediately, and
this warning:

Warning (package): Unnecessary call to ‘package-initialize’ in init file

I tried with/without the below in the first line of the file, but there was no difference.
 -*- no-byte-compile: t; lexical-binding: t; -*-

I also tried to comment out this line from pre-early-init.el:
;; (setq minimal-emacs-ui-features '(context-menu tool-bar menu-bar dialogs tooltips))

no difference either.

Maybe I should try a complete re-install?

**Comment by jamescherti** [comment]
The code snippet above works flawlessly on Emacs 30 with the latest version of minimal-emacs.d (Nov. 14: 0bb7705a725f3aeb0ddb59e51e2dedfdc2b18e69):
![image](https://github.com/user-attachments/assets/e991427d-ed59-4277-b962-7f46f48c665e)

Which version of Emacs are you using?

**Comment by jamescherti** [comment]
Would you be able to try using a separate minimal-emacs.d installation?

```
git clone https://github.com/jamescherti/minimal-emacs.d ~/.test-minimal-emacs.d
```

Add the following code snippet to `~/.test-minimal-emacs.d/post-early-init.el`
```
;;; post-init.el --- Early Init -*- no-byte-compile: t; lexical-binding: t; -*-
    
(setq minimal-emacs-package-initialize-and-refresh nil)

;; Initialize packages in here instead of init.el
(progn
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (eval-when-compile
    (require 'use-package)))

(use-package tomorrow-night-deepblue-theme
  :ensure t
  :config
  ;; Disable all themes and load the Tomorrow Night Deep Blue theme
  (mapc #'disable-theme custom-enabled-themes)
  (load-theme 'tomorrow-night-deepblue t))
    
(provide 'post-early-init)
```
And run Emacs using:

    emacs --init-directory ~/.test-minimal-emacs.d/

**Comment by jamescherti** [comment]
(EDIT: I also added `:demand t`)

**Comment by eborgbjerg** [comment]
I have 29.3:
emacs/noble,noble,now 1:29.3+1-1ubuntu2

and I pulled from master on minimal-emacs.d about 1 hour ago.

I'll try the separate install dir as you suggested above, and get back here with my results.
And I'll see if I can try out Emacs v 30.x also.

**Comment by eborgbjerg** [comment]
Still on Emacs 29.3, running from a freshly cloned git plus the post-early-init.el from above, I get the same behavior as when I ran from my usual directory (actually I start emacs with  --init-directory there also).

I'll get Emacs 30.x installed somehow and see how that works then :-)

**Comment by jamescherti** [comment]
That sounds good, @eborgbjerg. Please keep me updated!

**Comment by eborgbjerg** [comment]
I cloned the code from the git repo of Emacs, switched to branch emacs-30, reset that to the tagged commit for 30.0.92 and installed that as per the build instructions in INSTALL.REPO.
This installed the new version in /usr/local/bin/emacs
So I ran

/usr/local/bin/emacs --init-directory ~/.test-minimal-emacs.d/

but the result is the same as with Emacs 29.3.

I tried the above both with X and Wayland (not that I could relate that to the error message, but then again one never knows..).

It's a quite intriguing issue :-)
I'll try and see if I can reproduce this on other machines, other OS'es also.
Let me know if you want me to try out other things too.

Thanks,
Ejner

**Comment by eborgbjerg** [comment]
All in all I tried these combinations

Ubuntu 24.04 + Gnome desktop
   Emacs 29.3 (from apt)
   Emacs 30.0.92 (compiled by hand)
Ubuntu 22.04 + Gnome desktop
   Emacs 29.4 (snap)
FreeBSD 14.1 + KDE desktop
   Emacs 29.4 (pkg install)

with the 
emacs --init-directory ~/.test-minimal-emacs.d/
plus the post-early-init.el adaptation as above.

In all cases I see the blue theme being briefly displayed, then it disappears again and the warning:
Warning (package): Unnecessary call to ‘package-initialize’ in init file

**Comment by jamescherti** [comment]
Odd.

I have the same configuration, but the background remains unchanged. I have tested this setup on Debian Bookworm, Gentoo, and Arch Linux.
![image](https://github.com/user-attachments/assets/c071c829-a7da-4716-8cff-f866e19ce4f6)

I tested it on Debian Bookworm, Gentoo, and Arch Linux.

Here's an improved version of your request:

Could you share your configuration files as they are? Specifically, please paste all `~/.test-minimal-emacs.d/post*.el` and `~/.test-minimal-emacs.d/pre*.el` files here.

**Comment by jamescherti** [comment]
Also, here are my compile flags: 
```
--enable-link-time-optimization --with-gnutls --disable-build-details --with-wide-int --disable-gc-mark-trace --with-mailutils --without-pop --with-tree-sitter --with-xml2 --without-gpm --with-native-compilation --with-modules --with-threads --with-zlib --with-xdbe --with-x-toolkit=gtk3 --with-toolkit-scroll-bars --without-pgtk --without-ns --without-xaw3d --with-cairo --with-cairo-xcb --with-harfbuzz --without-xft --without-m17n-flt --without-libotf --with-file-notification=inotify --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xpm --with-webp --with-sqlite3 --with-xinput2 --without-lcms2 --without-dbus --without-kerberos --without-kerberos5 --without-sound --without-gconf --without-gsettings --without-libsystemd --without-selinux --without-xim --with-dumping=pdumper --disable-largefile
```

**Comment by jamescherti** [comment]
Additionally, consider renaming `~/.emacs.d` to `~/.emacs.d.old` before running your tests to ensure that nothing from `~/.emacs.d` is being loaded inadvertently.

**Comment by eborgbjerg** [comment]
I also feel that the difference must come down to our environments differences, I will get back on the above points over this weekend.

**Comment by eborgbjerg** [comment]
Edit: The issue also goes away if I rename .emacs + .emacs.d and continue to use the --init-directory option pointing to the dir where minimal-emacs was cloned to.
So it could also be that the actual content of .emacs + .emacs.d was used by design, so maybe it's not a real bug... :thinking:

**Comment by jamescherti** [comment]
That's great news! It's good to know we've identified the root cause of your issue.

After running a few tests, I observed the following behavior: When `~/.emacs` exists and `--init-directory` is specified, Emacs loads `~/.emacs` instead of `init.el` from the specified `--init-directory`.

Thank you once again for your patience and investigative skills. I appreciated working on this issue with you, @eborgbjerg.

**Comment by jamescherti** [comment]
I added a summary of our discussion to the README.md: https://github.com/jamescherti/minimal-emacs.d?tab=readme-ov-file#install-minimal-emacsd

**Comment by eborgbjerg** [comment]
Thank you for all your help :-)  And for creating minimal-emacs.d which is exactly what I was looking for!

**Comment by jamescherti** [comment]
You're very welcome! It was a pleasure to help. I'm glad that minimal-emacs.d is exactly what you were looking for. I, too, was looking for something like minimal-emacs.d when I started using Emacs (a bloat-free, optimized kit to start the Emacs journey).
