### ISSUE TITLE
Suggestions for .gitignore

### ISSUE THREAD

**Issue by eborgbjerg** [jamescherti/minimal-emacs.d#19]
Hello :-)

It seems that eww stores some urls under /url
so maybe that would be nice to add to .gitignore

Also some auto-saved files got saved in directory /autosave

**Comment by jamescherti** [comment]
Hello @eborgbjerg,

Thank you for your suggestion. I have added `/autosave/`.

For `/url`, could you check if this one is specific to your configuration? How can I make eww create this directory?

**Comment by jamescherti** [comment]
Thank you for checking this. I have added `/url` to the `.gitignore` file.
