### ISSUE TITLE
Starting with --init-directory

### ISSUE THREAD

**Issue by oatmealm** [jamescherti/minimal-emacs.d#2]
I'm curious why this doesn't work... it won't load the init files at all (I'm skipping site-lisp).

```
emacs --init-directory ~/.config/minimal-emacs.d/ -nsl
```

**Comment by jamescherti** [comment]
I tried the same and it worked for me:
```
git clone https://github.com/jamescherti/minimal-emacs.d  ~/.config/minimal-emacs.d
git -C ~/.config/minimal-emacs.d pull
echo '(message "Test")' >> ~/.config/minimal-emacs.d/post-init.el
```

When I execute:
```
emacs --init-directory ~/.config/minimal-emacs.d/ -nsl
```

I see "Test" in the `*Messages*` buffer.

Could you please try to do the same? Do you see Test?

**Comment by oatmealm** [comment]
Yep. Works. I think I misunderstood the load order. 
Thank you.

**Comment by jamescherti** [comment]
You're welcome, @oatmealm . I'm glad it works for you. If you have any more questions, feel free to ask!
