### ISSUE TITLE
Not compatible with org-modern

### ISSUE THREAD

**Issue by Makesesama** [jamescherti/minimal-emacs.d#20]
I have updated your starter kit recently and found odd behavior. If i try to use org-modern the buffer is not scrollable by mouse anymore and constantly resets the window to show  the buffer with the point at the center. I have debugged this and found that `(setq-default make-window-start-visible t)` is the problem. Commenting this out fixes the issue.

I dont really know why this is happening, i just wanted to document this here so someone more capable could fix this or correct me.

org-modern config:
```elisp
(use-package org-modern
  :hook (org-mode . global-org-modern-mode)
  ;; :hook (org-agenda-finalize . org-modern-agenda)
  :after org
  :config
  ;; (with-eval-after-load 'org (global-org-modern-mode))
  ;; Option 1: Per buffer
  ;; (add-hook 'org-mode-hook #'org-modern-mode)
  (setq
   ;; Edit settings
   org-auto-align-tags nil
   org-tags-column 0
   org-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-insert-heading-respect-content t

   ;; Org styling, hide markup etc.
   org-hide-emphasis-markers t
   org-pretty-entities t
   org-ellipsis "…"

   ;; Agenda styling
   ;; org-agenda-tags-column 0
   ;; org-agenda-block-separator "?─"
   ;; org-agenda-time-grid
   ;; '((daily today require-timed)
   ;;   (800 1000 1200 1400 1600 1800 2000)
   ;;   " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
   ;; org-agenda-current-time-string
   ;; "◀── now ─────────────────────────────────────────────────"
   ))
```

Thanks for the nice starter kit :)

**Comment by Makesesama** [comment]
Another weird thing just happened: I got the scroll bug in a magit buffer.

Commenting out the mentioned line also fixes that.

**Comment by jamescherti** [comment]
Hello,

> Thanks for the nice starter kit :)

You're very welcome!

> I have updated your starter kit recently and found odd behavior. If i try to use org-modern the buffer is not scrollable by mouse anymore and constantly resets the window to show the buffer with the point at the center. I have debugged this and found that (setq-default make-window-start-visible t) is the problem. Commenting this out fixes the issue.

Can you test using a separate installation:
```
git clone https://github.com/jamescherti/minimal-emacs.d ~/.test-minimal-emacs.d
```

Add the following to `~/.test-minimal-emacs.d`:
```elisp
(use-package org-modern
  :hook (org-mode . global-org-modern-mode)
  ;; :hook (org-agenda-finalize . org-modern-agenda)
  :after org
  :config
  ;; (with-eval-after-load 'org (global-org-modern-mode))
  ;; Option 1: Per buffer
  ;; (add-hook 'org-mode-hook #'org-modern-mode)
  (setq
   ;; Edit settings
   org-auto-align-tags nil
   org-tags-column 0
   org-catch-invisible-edits 'show-and-error
   org-special-ctrl-a/e t
   org-insert-heading-respect-content t

   ;; Org styling, hide markup etc.
   org-hide-emphasis-markers t
   org-pretty-entities t
   org-ellipsis "…"

   ;; Agenda styling
   ;; org-agenda-tags-column 0
   ;; org-agenda-block-separator "?─"
   ;; org-agenda-time-grid
   ;; '((daily today require-timed)
   ;;   (800 1000 1200 1400 1600 1800 2000)
   ;;   " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
   ;; org-agenda-current-time-string
   ;; "◀── now ─────────────────────────────────────────────────"
   ))
```

Then run Emacs using:
```
emacs --init-directory ~/.test-minimal-emacs.d/
```

Do you still experience the same issue?

**Comment by jamescherti** [comment]
Additionally, what is the value of `scroll-conservatively` in *org-modern* buffers that cannot be scrolled with the mouse?

**Comment by Makesesama** [comment]
Hey, thanks for getting back so quickly.

Emacs version is 31.0.50. I tried with a default minimal-emacs.d exactly as you described. I added the org-modern config to the post-init.el and got the bug i described.

The value of `scroll-conservatively` is 10.

Hope this is of any help

**Comment by jamescherti** [comment]
Hello @Makesesama,

I've tried using Emacs 31 and noticed occasional jumping behavior. I tested this with an example org document from https://writequit.org/denver-emacs/presentations/files/example.org.html .

Does changing 'scroll-conservatively' to the following potentially resolve the issue?
```
(setq scroll-conservatively 101)
```

If the above doesn't work, does the following fix it?
```
(setq scroll-conservatively 10000)
```

**Comment by jamescherti** [comment]
I commented out `make-window-start-visible` in the latest version of `minimal-emacs.d`, just in case other users are experiencing the same issue. 

Please let me know the results of the tests above as soon if you have time to run them. (Because I commented out the variable, please set `make-window-start-visible` to `t` while performing these tests.)

**Comment by Makesesama** [comment]
Hey,  i now tried with `(setq scroll-conservatively 101)` and `(setq scroll-conservatively 10000)`. With both it was possible to scroll again, but it felt really stuttery and you could not really follow where you were scrolling.

At this time its probably best to disable as you did and wait for someone to investigate why this is happening. Sadly i dont really have the time right now. I will come back if i had a look though.

Thanks for handling this :)

**Comment by jamescherti** [comment]
> Hey, i now tried with (setq scroll-conservatively 101) and (setq scroll-conservatively 10000). With both it was possible to scroll again, but it felt really stuttery and you could not really follow where you were scrolling.

Thank you for confirming. I really dislike having `scroll-conservatively` set below 101. However, it can be useful to set it to 10 for specific jumping functions, such as searching for the next occurrence or jumping to a definition. Perhaps this option could be configured on a per-function basis.

> At this time its probably best to disable as you did and wait for someone to investigate why this is happening. Sadly i dont really have the time right now. I will come back if i had a look though.

Yes, it is better to disable it for now.  

It's unfortunate. I really like this option because it allows for better management of the first line when folding is used (e.g., outline-indent, outline-minor-mode, etc.).

When you have time, please consider reporting this issue to the emacs-devel mailing list.

> Thanks for handling this :)

My pleasure!
