### ISSUE TITLE
Lisp nesting exceeds 'max-lisp-eval-depth'

### ISSUE THREAD

**Issue by JordanAnthonyKing** [jamescherti/minimal-emacs.d#3]
Although startup is still fast (af) I find this message on startup a bit concerning. It seems to be caused by following this piece of advice from the readme:
```
(setq minimal-emacs-user-directory user-emacs-directory)
(setq minimal-emacs-var-dir
      (expand-file-name "var/" minimal-emacs-user-directory))
(setq package-user-dir (expand-file-name "elpa" minimal-emacs-var-dir))
(setq user-emacs-directory minimal-emacs-var-dir)
```

**Comment by jamescherti** [comment]
Hello @JordanAnthonyKing !

Thank you for your feedback.

I use the same code in my Emacs configuration and It works flawlessly:
```elisp
(setq minimal-emacs-user-directory user-emacs-directory)
(setq minimal-emacs-var-dir
      (expand-file-name "var/" minimal-emacs-user-directory))
(setq package-user-dir (expand-file-name "elpa" minimal-emacs-var-dir))
(setq user-emacs-directory minimal-emacs-var-dir)
```

Did you place the code in your `pre-early-init.el`?

**Comment by JordanAnthonyKing** [comment]
It's in pre-early-init, I have the latest version, changing that line doesn't help however if I uncomment every line the message goes away, but this could be related to an issue with package installs as I'm currently having issues verifying signatures from elpa.

**Comment by jamescherti** [comment]
Could you please try the following steps for a fresh installation:

1. Clone the repository:
   ```sh
   git clone https://github.com/jamescherti/minimal-emacs.d ~/test-minimal-emacs.d
   ```

2. Create the `pre-early-init.el` file with the following content:
   ```sh
   echo '(setq minimal-emacs-var-dir (expand-file-name "var/" minimal-emacs-user-directory))
   (setq package-user-dir (expand-file-name "elpa/" minimal-emacs-var-dir))
   (setq user-emacs-directory minimal-emacs-var-dir)' > ~/test-minimal-emacs.d/pre-early-init.el
   ```

3. Start Emacs using the new configuration directory:
   ```sh
   emacs --init-directory ~/test-minimal-emacs.d/
   ```

Does this setup produce the same issue?

**Comment by JordanAnthonyKing** [comment]
The exact line seems to be:

(setq package-user-dir (expand-file-name "elpa" minimal-emacs-var-dir))

This is with no other customisation of my own and running emacs 30

**Comment by jamescherti** [comment]
I'm also running Emacs 30, and the lines above work perfectly for me.

Have you tried using `~/test-minimal-emacs.d`?

**Comment by JordanAnthonyKing** [comment]
>Have you tried using ~/test-minimal-emacs.d?
![image](https://github.com/user-attachments/assets/45b6a607-300c-49f3-9b30-02a42b7ada13)

**Comment by jamescherti** [comment]
Have you included echo in the pre-early-init.el? If that's the case:

Here’s the content of `~/test-minimal-emacs.d/pre-early-init.el`:
```
;; Reducing clutter in ~/.emacs.d by redirecting files to ~/emacs.d/var/
(setq minimal-emacs-var-dir (expand-file-name "var/" minimal-emacs-user-directory))
(setq package-user-dir (expand-file-name "elpa/" minimal-emacs-var-dir))
(setq user-emacs-directory minimal-emacs-var-dir)
```

Could you please try again using the content the above `pre-early-init.el`?

**Comment by JordanAnthonyKing** [comment]
Nothing in that case

**Comment by jamescherti** [comment]
If you get nothing, it means it is working.
