### ISSUE TITLE
Custom file not being read?

### ISSUE THREAD

**Issue by JordanAnthonyKing** [jamescherti/minimal-emacs.d#5]
I haven't set the custom file to nil as shown in the readme, but I'm finding warnings I've asked to be ignored are written to custom.el but aren't actually being hidden. Is there some sort of mismatch between reading and writing to it?

**Comment by jamescherti** [comment]
Could you please share the value of your `custom-file` variable and the specific warnings you're encountering?

**Comment by jamescherti** [comment]
Try the following:
- Load customizations (`custom.el`) earlier, in your `post-early-init.el` file.
- Ensure that the Elpaca bootstrap is in `pre-init.el` (not in one of the *early-init.el files).

Does this fix the issue?"

**Comment by JordanAnthonyKing** [comment]
That seems to have done the trick, feels a bit hacky tho :L

**Comment by jamescherti** [comment]
Glad it worked! Thanks for confirming, @JordanAnthonyKing!
