### ISSUE TITLE
Symbol's function definition is void: tool-bar-setup

### ISSUE THREAD

**Issue by ejuarezg** [jamescherti/minimal-emacs.d#6]
Hi, I'm getting the error listed in the title. I am only able to bootstrap by commenting out the code block in line 258 of early-init.el.

**Comment by jamescherti** [comment]
Which version of Emacs are you using?

I have just committed a quick fix to the main branch. Could you please update your local copy with `git pull`, try to execute Emacs and confirm if it is working?

**Comment by ejuarezg** [comment]
That fixed it. Thank you! I should have mentioned that I'm using the [Cosmos version](https://github.com/jart/cosmopolitan) of Emacs, which provides version 29.3 but may not be built with all the flags and features Emacs has to offer.

**Comment by jamescherti** [comment]
You're welcome, @ejuarezg! I'm glad to hear that the fix worked for you. It was definitely a very niche bug. Thank you for mentioning the portable Cosmos version of Emacs (context like that is always helpful, especially with different builds). If you encounter any more issues or have further questions, feel free to open another issue.
