### ISSUE TITLE
suggestion: use-package-always-defer 

### ISSUE THREAD

**Issue by jonasagx** [jamescherti/minimal-emacs.d#7]
Thank you for sharing your cool project. I've included some settings into my own config and things look snappier.

One thing I'd suggest is the use of `use-package-always-defer t`. I see it wasn't used before by this repo, which prompted me to suggest it.

**Comment by jamescherti** [comment]
It’s great to hear that things are running more smoothly for you. Please do not hesitate to send me any benchmarks, including the time it takes to start Emacs before and after incorporating the changes into your configuration.

I prefer not to add `use-package-always-defer t` to `minimal-emacs.d` for the following reasons:
1. Enforcing `use-package-always-defer t` might constrain users who prefer more immediate access to certain packages. Customization options should ideally accommodate various preferences, allowing users to enable or disable deferring based on their specific needs.
2. It might increase complexity for users who are unfamiliar with `use-package` and package deferral. (`use-package-always-defer t` assumes that users are comfortable with the potential consequences of deferring packages, which may not always align with their preferences or use cases.)

I prefer letting the users decide if they want to defer packages using `use-package-always-defer t`. 

Thank you for your suggestion, @jonasagx .
