### ISSUE TITLE
Ignore additional projectile bookmarks and tree-sitter directory

### ISSUE THREAD

**Issue by jbromley** [jamescherti/minimal-emacs.d#9]
After configuring with minimal-emacs.d and running for a few days, I checked my `~/.emacs.d` directory and saw that the `projectile-bookmarkds.eld` and `tree-sitter` directories were untracked. Would it be reasonable to add these to the `.gitignore` file?

**Comment by jbromley** [comment]
I just submitted a pull request for this.

**Comment by jamescherti** [comment]
I merged it. Thanks, @jbromley .
